
soundManager = {
  ok: function() {},
  supported: function() {},
  getMovie: function() {},
  createSound: function() {},
  destroySound: function() {},
  load: function() {},
  unload: function() {},
  onposition: function() {},
  play: function() {},
  start: function() {},
  setPosition: function() {},
  stop: function() {},
  stopAll: function() {},
  pause: function() {},
  pauseAll: function() {},
  resume: function() {},
  resumeAll: function() {},
  togglePause: function() {},
  setPan: function() {},
  setVolume: function() {},
  mute: function() {},
  muteAll: function() {},
  unmute: function() {},
  unmuteAll: function() {},
  toggleMute: function() {},
  getMemoryUse: function() {},
  disable: function() {},
  canPlayMIME: function() {},
  canPlayURL: function() {},
  canPlayLink: function() {},
  getSoundById: function() {},
  onready: function() {},
  ontimeout: function() {},
  _writeDebug: function() {},
  _wD: function() {},
  _debug: function() {},
  reboot: function() {},
  getMoviePercent: function() {},
  beginDelayedInit: function() {},
  destruct: function() {},
  _setSandboxType: function() {},
  _externalInterfaceOK: function() {},

  flashVersion: {},
  debugMode: {},
  debugFlash: {},
  useConsole: {},
  consoleOnly: {},
  waitForWindowLoad: {},
  bgColor: {},
  useHighPerformance: {},
  flashPollingInterval: {},
  flashLoadTimeout: {},
  wmode: {},
  allowScriptAccess: {},
  useFlashBlock: {},
  useHTML5Audio: {},
  html5Test: {},
  preferFlash: {},
  audioFormats: {},
  defaultOptions: {},
  flash9Options: {},
  movieStarOptions: {},
  movieID: {},
  id: {},
  swfCSS: {},
  debugID: {},
  debugURLParam: {},
  versionNumber: {},
  version: {},
  movieURL: {},
  url: {},
  altURL: {},
  swfLoaded: {},
  enabled: {},
  o: {},
  oMC: {},
  sounds: {},
  soundIDs: {},
  muted: {},
  specialWmodeCase: {},
  didFlashBlock: {},
  filePattern: {},
  filePatterns: {
    flash8: {},
    flash9: {}
  },
  features: {
    buffering: {},
    peakData: {},
    waveformData: {},
    eqData: {},
    movieStar: {}
  },
  sandbox: {
    type: {},
    types: {},
    description: {},
    noRemote: {},
    noLocal: {}
  },
  hasHTML5: {},
  html5: {
    usingFlash: {}
  },
  flash: {},
  html5Only: {},
  ignoreFlash: {},
  mimePattern: {},
  useAltURL: {},
  _global_a: {}
}
