/*
Copyright (C) 2011 by Benjamin McGregor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/
soundManager.url="./lib/flash/soundmanager2/";soundManager.debugMode=!1;soundManager.debugFlash=!1;soundManager.flashVersion=9;soundManager.useHTML5Audio=!0;
define("General.Notification.Observable","abstract").assign({observers:null,state:null,Observable:function(){this.observers=[];this.state={observable:this}},_Observable:function(){delete this.observers;delete this.state},addObserver:function(a){if(!a.Observer)return null;this.observers.splice(0,0,a);return this},removeObserver:function(a){var b;if(!a.Observer)return null;for(b in this.observers)this.observers[b]===a&&this.observers.splice(b,1);return this},notify:function(){for(var a in this.observers)this.observers[a].update!==
null&&this.observers[a].update(this,this.state)}});define("General.Notification.Observer","abstract").assign({update:function(){throw Error("Unimplemented update fired.");}});define("IGE.Exceptions.IGEException").assign({text:null,context:null,IGEException:function(a,b){this.text=a;this.context=typeof b==="object"?b:null},toString:function(){return"IGEException: "+this.text},getContext:function(){return this.context}});using("IGE.Exceptions");
define("IGE.Exceptions.IGEInvalidIdException").extend("IGEException").assign({IGEInvalidIdException:function(a,b){this.IGEException(a,b)},toString:function(){return"IGEInvalidIdException: "+this.text}});unusing("IGE.Exceptions");using("IGE.Exceptions");define("IGEInvalidSourceException").extend("IGEException").assign({IGEInvalidSourceException:function(a,b){this.IGEException(a,b)},toString:function(){return"IGEInvalidSourceException: "+this.text}});unusing("IGE.Exceptions");using("IGE.Exceptions");
define("IGE.Exceptions.IGEInvalidTypeException").extend("IGEException").assign({IGEInvalidTypeException:function(a,b){this.IGEException(a,b)},toString:function(){return"IGEInvalidTypeException: "+this.text}});unusing("IGE.Exceptions");using("IGE.Exceptions");define("IGERemovalException").extend("IGEException").assign({IGERemovalException:function(a,b){this.IGEException(a,b)},toString:function(){return"IGERemovalException: "+this.text}});unusing("IGE.Exceptions");using("IGE.Exceptions");
define("IGE.Exceptions.IGEImageException").extend("IGEException").assign({IGEImageException:function(a,b){this.IGEException(a,b)},toString:function(){return"IGEImageException: "+this.text}});unusing("IGE.Exceptions");using("IGE.Exceptions");define("IGE.Exceptions.IGESoundException").extend("IGEException").assign({IGESoundException:function(a,b){this.IGEException(a,b)},toString:function(){return"IGESoundException: "+this.text}});unusing("IGE.Exceptions");using("IGE.Exceptions");
define("IGE.Exceptions.IGEUnimplementedException").extend("IGEException").assign({IGEUnimplementedException:function(a,b){this.IGEException(a,b)},toString:function(){return"IGEUnimplementedException: "+this.text+(typeof this.context==="object"?": "+this.context.constructor.name:"")}});unusing("IGE.Exceptions");using("IGE.Util");
define("IGE.Util.IGEPoint").assign({x:null,y:null,IGEPoint:function(a,b){if(typeof a!=="number"||typeof b!=="number")throw new IGEInvalidTypeException("IGEPoint: x and y must be numberic types.",this);this.x=a;this.y=b},_IGEPoint:function(){},getX:function(){return this.x},getY:function(){return this.y},setX:function(a){if(typeof a!=="number")throw new IGEInvalidTypeException("x must be a number, got "+typeof a+".",this);this.x=a;return this},setY:function(a){if(typeof a!=="number")throw new IGEInvalidTypeException("y must be a number, got "+
typeof a+".",this);this.y=a;return this},distance:function(a){if(typeof a!=="object"||!a.IGEPoint)throw new IGEInvalidTypeException("distance takes an IGEPoint object.",this);return Math.sqrt(Math.pow(a.getX()-this.x,2)+Math.pow(a.getY()-this.y,2))}});using("IGE.Util");using("IGE.Util");
define("IGE.Util.IGEVector").assign({x:null,y:null,unit:null,IGEVector:function(a,b){if(typeof a!=="number"||typeof b!=="number")throw new IGEInvalidTypeException("IGEVector: x and y must be numeric types.",this);this.x=a;this.y=b},_IGEVector:function(){delete this.x;delete this.y;delete this.unit},getX:function(){return this.x},setX:function(a){if(typeof a!=="number")throw new IGEInvalidTypeException("setX: value must be a number, got "+typeof a+".",this);this.x=a;return this},addX:function(a){if(typeof a!==
"number")throw new IGEInvalidTypeException("addX: value must be a number, got "+typeof a+".",this);this.x+=a;return this},subtractX:function(a){if(typeof a!=="number")throw new IGEInvalidTypeException("subtractX: value must be a number, got "+typeof a+".",this);this.x-=a;return this},multiplyX:function(a){if(typeof a!=="number")throw new IGEInvalidTypeException("multiplyX: value must be a number, got "+typeof a+".",this);this.x*=a;return this},divideX:function(a){if(typeof a!=="number")throw new IGEInvalidTypeException("divideX: value must be a number, got "+
typeof a+".",this);this.x/=a;return this},getY:function(){return this.y},setY:function(a){if(typeof a!=="number")throw new IGEInvalidTypeException("setY: value must be a number, got "+typeof a+".",this);this.y=a;return this},addY:function(a){if(typeof a!=="number")throw new IGEInvalidTypeException("addY: value must be a number, got "+typeof a+".",this);this.y+=a;return this},subtractY:function(a){if(typeof a!=="number")throw new IGEInvalidTypeException("subtractY: value must be a number, got "+typeof a+
".",this);this.y-=a;return this},multiplyY:function(a){if(typeof a!=="number")throw new IGEInvalidTypeException("multiplyY: value must be a number, got "+typeof a+".",this);this.y*=a;return this},divideY:function(a){if(typeof a!=="number")throw new IGEInvalidTypeException("divideY: value must be a number, got "+typeof a+".",this);this.y/=a;return this},add:function(a){if(typeof value!=="object"||!a.IGEVector)throw new IGEInvalidTypeException("add: value must be an IGEVector object.",+this);this.addX(a.getX());
this.addY(a.getY());return this},subtract:function(a){if(typeof value!=="object"||!a.IGEVector)throw new IGEInvalidTypeException("subtract: value must be an IGEVector object.",+this);this.subtractX(a.getX());this.subtractY(a.getY());return this},multiply:function(a){if(typeof value!=="object"||!a.IGEVector)throw new IGEInvalidTypeException("multiply: value must be an IGEVector object.",+this);this.multiplyX(a.getX());this.multiplyY(a.getY());return this},divide:function(a){if(typeof value!=="object"||
!a.IGEVector)throw new IGEInvalidTypeException("divide: value must be an IGEVector object.",+this);this.divideX(a.getX());this.divideY(a.getY());return this},unitVector:function(){var a=this.magnitude();if(!this.unit)this.unit=new IGEVector(0,0);this.unit.setX(this.getX()/a);this.unit.setY(this.getY()/a);return this.unit},magnitude:function(){return Math.sqrt(Math.pow(this.x,2)+Math.pow(this.y,2))},directionRad:function(){return Math.atan(this.y/this.x)},directionDeg:function(){return this.directionRad()*
(180/Math.PI)}});using("IGE.Util");using("IGE.Modification");define("IGE.Modification.IGEModifier","abstract").assign({duration:null,activate:abstractFunction(),deactivate:abstractFunction()});IGE.Modification.IGEModifier.add=1;IGE.Modification.IGEModifier.subtract=2;IGE.Modification.IGEModifier.multiply=3;IGE.Modification.IGEModifier.divide=4;IGE.Modification.IGEModifier.replace=5;unusing("IGE.Modification");using("IGE.Graphics");
IGE.Graphics.IGEStrata={background1:5,background2:10,far:15,semiFar:20,moderate:25,semiNear:40,near:50};
with(namespace("General.Notification","IGE.Graphics","IGE.Audio"))define("IGE.IGEArea").extend(Observer,Observable).assign({posNum:null,posCopy:null,center:null,id:null,imageHandler:null,soundHandler:null,displayElement:null,panel:null,parent:null,preUpdateFunc:null,postUpdateFunc:null,isVerbose:null,friction:null,frictionCopy:null,modifiers:null,defaults:{x:0,y:0,width:0,height:0,friction:0,strata:IGEStrata.moderate,id:"IGEArea",panel:"DEFAULT",parent:null,verbose:!1},IGEArea:function(a){a||(a={});
$.extend(a,$.extend({},this.defaults,a));this.isVerbose=a.verbose;this.Observable();this.Observer();this.panel=typeof a.panel==="string"?getIGEPanel(a.panel):typeof a.panel==="object"?a.panel.IGEPanel!==null?a.panel:null:null;this.id=a.id;this.id===this.defaults.id&&(this.id+=IGE.IGEArea.IGE_AREA_INDEX);IGE.IGEArea.IGE_AREA_INDEX++;this.debug("IGEArea: set id to "+this.id+".");this.posNum={x:a.x,y:a.y,width:a.width,height:a.height};this.posCopy={x:null,y:null,width:null,height:null};this.center=new IGEPoint(this.posNum.x+
this.posNum.width/2,this.posNum.y+this.posNum.height/2);this.displayElement=$(document.createElement("div"));this.displayElement.addClass("IGEArea");this.displayElement.attr("id",this.id);this.displayElement.css("z-index",a.strata);this.debug("IGEArea: display element for "+this.id+" has been created.");this.modifiers=[];this.friction=typeof a.friction==="number"?new IGEVector(a.friction,a.friction):typeof a.friction==="object"&&typeof a.friction.horizontal==="number"&&typeof a.friction.vertical===
"number"?new IGEVector(a.friction.horizontal,a.friction.vertical):typeof a.friction==="object"&&a.friction.IGEVector?a.friction:new IGEVector(0,0);this.debug("IGEObject: friction values hae been set.");this.frictionCopy=new IGEVector(0,0);with(IGE.Graphics)this.imageHandler=new IGEImageHandler({area:this});with(IGE.Audio)this.soundHandler=new IGESoundHandler({area:this});this.debug("IGEArea: image and sound handlers for "+this.id+" have been created.");this.preUpdateFunc=[];this.postUpdateFunc=[];
this.parent=a.parent;this.setPos();this.setWidth();this.setHeight();this.debug("IGEArea construction finished");return this},_IGEArea:function(){this._Observer();this._Observable()},setPos:function(a,b){if(typeof a==="number")this.posNum.x=a;if(typeof b==="number")this.posNum.y=b;this.getDisplayElement().css("left",this.posNum.x+"px").css("bottom",this.posNum.y+"px")},setWidth:function(a){if(typeof a==="number")this.posNum.width=a;this.getDisplayElement().css("width",this.posNum.width+"px")},setHeight:function(a){if(typeof a===
"number")this.posNum.height=a;this.getDisplayElement().css("height",this.posNum.height+"px")},getPos:function(){var a,b;with(namespace("IGE.Modification")){this.posCopy.x=this.posNum.x;this.posCopy.y=this.posNum.y;this.posCopy.width=this.posNum.width;this.posCopy.height=this.posNum.height;for(a in this.modifiers){if(this.modifiers[a].x)switch(b=this.modifiers[a].x,b.type){case IGEModifier.add:this.posCopy.x+=b.value;break;case IGEModifier.subtract:this.posCopy.x-=b.value;break;case IGEModifier.multiply:this.posCopy.x*=
b.value;break;case IGEModifier.divide:this.posCopy.x/=b.value;break;case IGEModifier.replace:this.posCopy.x=b.value}if(this.modifiers[a].y)switch(b=this.modifiers[a].y,b.type){case IGEModifier.add:this.posCopy.y+=b.value;break;case IGEModifier.subtract:this.posCopy.y-=b.value;break;case IGEModifier.multiply:this.posCopy.y*=b.value;break;case IGEModifier.divide:this.posCopy.y/=b.value;break;case IGEModifier.replace:this.posCopy.y=b.value}if(this.modifiers[a].width)switch(b=this.modifiers[a].width,
b.type){case IGEModifier.add:this.posCopy.width+=b.value;break;case IGEModifier.subtract:this.posCopy.width-=b.value;break;case IGEModifier.multiply:this.posCopy.width*=b.value;break;case IGEModifier.divide:this.posCopy.width/=b.value;break;case IGEModifier.replace:this.posCopy.width=b.value}if(this.modifiers[a].height)switch(b=this.modifiers[a].height,b.type){case IGEModifier.add:this.posCopy.height+=b.value;break;case IGEModifier.subtract:this.posCopy.height-=b.value;break;case IGEModifier.multiply:this.posCopy.height*=
b.value;break;case IGEModifier.divide:this.posCopy.height/=b.value;break;case IGEModifier.replace:this.posCopy.height=b.value}}this.getDisplayElement().css("width",this.posCopy.width+"px");this.getDisplayElement().css("height",this.posCopy.height+"px")}return this.posCopy},addModifier:function(a){if(typeof a!=="object"&&a.IGEModifier)throw new IGEInvalidTypeException("addModifier takes an IGEModifier object",this);this.modifiers.splice(this.modifiers.length,0,a);a.activate(this)},removeModifier:function(a){var b;
if(typeof a==="string")for(b in this.modifiers){if(this.modifiers[b][a]){this.modifiers[b].deactivate(this);this.modifiers.splice(b,1);break}}else if(typeof a==="object"&&a.IGEModifier)for(b in this.modifiers){if(this.modifiers[b]===a){this.modifiers[b].deactivate(this);this.modifiers.splice(b,1);break}}else throw this.displayError("removeModifier takes an IGEModifier object or string"),new IGEInvalidTypeException("removeModifier takes an IGEModifier object or string",this);return this},getCenter:function(){var a=
this.getPos();this.center.setX(a.x+a.width/2);this.center.setY(a.y+a.height/2);return this.center},getFriction:function(){var a,b;this.frictionCopy.setX(this.friction.getX());this.frictionCopy.setY(this.friction.getY());for(a in this.modifiers){if(this.modifiers[a].frictionHorizontal)switch(b=this.modifiers[a].frictionHorizontal,b.type){case IGEObjectModifier.add:this.frictionCopy.addX(b.value);break;case IGEObjectModifier.subtract:this.frictionCopy.subtractX(b.value);break;case IGEObjectModifier.multiply:this.frictionCopy.multiplyX(b.value);
break;case IGEObjectModifier.divide:this.frictionCopy.divideX(b.value);break;case IGEObjectModifier.replace:this.frictionCopy.setX(b.value)}if(this.modifiers[a].frictionVerticle)switch(b=this.modifiers[a].frictionVerticle,b.type){case IGEObjectModifier.add:this.frictionCopy.addY(b.value);break;case IGEObjectModifier.subtract:this.frictionCopy.subtractY(b.value);break;case IGEObjectModifier.multiply:this.frictionCopy.multiplyY(b.value);break;case IGEObjectModifier.divide:this.frictionCopy.divideY(b.value);
break;case IGEObjectModifier.replace:this.frictionCopy.setY(b.value)}}return this.frictionCopy},isAbove:function(a){return this.isAboveOffset(a,0)},isAboveOffset:function(a,b){if(!a.IGEArea)return!1;var c=this.getPos(),d=a.getPos();return c.y+b>=d.y+d.height},isBelow:function(a){return this.isBelowOffset(a,0)},isBelowOffset:function(a,b){if(!a.IGEArea)return!1;var c=this.getPos(),d=a.getPos();return c.y+c.height+b<=d.y},isLeftOf:function(a){return this.isLeftOfOffset(a,0)},isLeftOfOffset:function(a,
b){if(!a.IGEArea)return!1;var c=this.getPos(),d=a.getPos();return c.x+c.width+b<=d.x},isRightOf:function(a){return this.isRightOfOffset(a,0)},isRightOfOffset:function(a,b){if(!a.IGEArea)return!1;var c=this.getPos(),d=a.getPos();return c.x+b>=d.x+d.width},intersects:function(a){return this.intersectsOffset(a,0,0)},intersectsOffset:function(a,b,c){return this.intersectsYOffset(a,c)&&this.intersectsXOffset(a,b)},intersectsY:function(a){return this.intersectsYOffset(a,0)},intersectsYOffset:function(a,
b){if(typeof a!=="object"||!a.IGEArea||typeof b!=="number")throw new IGEInvalidTypeException("intersectsYOffset takes an IGEArea and numeric offset.",this);var c=this.getPos(),d=a.getPos();return c.y+b<=d.y&&c.y+c.height+b>=d.y||c.y+b>=d.y&&c.y+b<=d.y+d.height},intersectsX:function(a){return this.intersectsXOffset(a,0)},intersectsXOffset:function(a,b){if(typeof a!=="object"||!a.IGEArea||typeof b!=="number")throw new IGEInvalidTypeException("intersectsXOffset takes an IGEArea and numeric offset.",
this);var c=this.getPos(),d=a.getPos();return c.x+b<=d.x&&c.x+c.width+b>=d.x||c.x+b>=d.x&&c.x+b<=d.x+d.width},getParent:function(){return this.parent},setParent:function(a){if(!a.IGEArea)return null;this.parent=a;return this},getImageHandler:function(){return this.imageHandler},getSoundHandler:function(){return this.soundHandler},getID:function(){return this.id},getDisplayElement:function(){return this.displayElement},displayError:function(a){this.panel&&this.panel.displayError(a)},displayWarning:function(a){this.panel&&
this.panel.displayWarning(a)},displayInfo:function(a){this.panel&&this.panel.displayInfo(a)},update:function(){for(var a in this.preUpdateFunc)this.preUpdateFunc[a]();this.updateState();for(a in this.postUpdateFunc)this.postUpdateFunc[a]()},updateInit:function(a){if(typeof a!=="function")throw new IGEInvalidTypeException("updateInit takes a function argument",this);this.preUpdateFunc.push(a);return this},updateState:function(){},updateFinal:function(a){if(typeof a!=="function")throw new IGEInvalidTypeException("updateFinal takes a function argument",
this);this.postUpdateFunc.push(a);return this},interactWith:function(a){if(!a.IGEArea)return null;return this},impact:function(a){if(!a.IGEArea)return null;return this},show:function(){this.getDisplayElement().show();return this},hide:function(){this.getDisplayElement().hide();return this},isShown:function(){return this.getDisplayElement().css("display")!=="none"},debug:function(a){this.isVerbose&&this.displayInfo(a)}}).statics({IGE_AREA_INDEX:0});using("IGE");using("IGE.Modification");
define("IGE.Modification.IGEAreaModifier","abstract").extend("IGEModifier").assign({x:null,y:null,width:null,height:null,frictionHorizontal:null,frictionVertical:null,activate:abstractFunction(IGEArea),deactivate:abstractFunction(IGEArea)});unusing("IGE");unusing("IGE.Modification");using("IGE");using("IGE.Audio");
define("IGE.Audio.IGESound").assign({id:null,source:null,handler:null,soundManagerReady:!1,soundObject:null,IGESound:function(a){var b=this;if(!typeof a==="object")throw new IGEInvalidTypeException("IGESound constructor expected Object",b);b.id=a.id;b.source=a.source;if(typeof b.id!=="string")throw b._IGESound(),new IGEInvalidIdException("IGESound constructor requires a valid String id to be set.",b);if(typeof b.source!=="string")throw b._IGESound(),new IGEInvalidSourceException("IGESound constructor requires a valid String source to be set.",
b);a.handler&&a.handler.IGESoundHandler&&a.handler.addSound(b);soundManager.onready(function(){b.soundManagerReady=!0;b.preload()});return b},_IGESound:function(){this.soundObject&&this.soundObject.destruct();delete this.id;delete this.source;delete this.handler;delete this.soundObject},play:function(){this.soundManagerReady&&this.handler&&this.soundObject.play()},mute:function(){this.soundObject.mute()},unmute:function(){this.soundObject.unmute()},stop:function(){this.soundObject.stop()},pause:function(){this.soundObject.pause()},
unpause:function(){this.soundObject.resume()},preload:function(){if(this.soundManagerReady)this.soundObject=soundManager.createSound({id:this.id,url:this.source,autoLoad:!0})}});unusing("IGE");unusing("IGE.Audio");using("IGE");using("IGE.Audio");using("General.Notification");
define("IGE.Audio.IGESoundHandler").extend("Observer").assign({sounds:null,soundsCopy:null,IGESoundHandler:function(){this.sounds={};this.soundsCopy={};return this},_IGESoundHandler:function(){delete this.sounds;delete this.soundsCopy},play:function(a){this.sounds[a].play()},addSound:function(a){if(typeof a!=="object"||!a.IGESound)throw new IGESoundException("Attempt to add an invalid sound.");this.sounds[a.id]&&this.removeSound(a.id);this.sounds[a.id]=a;a.handler=this;return this},removeSound:function(a){if(typeof a!==
"string")if(typeof a==="object"&&a.IGESound)a=a.id;else throw new IGESoundException("Unable to determine the id of sound to remove.");if(this.sounds[a])this.sounds[a].handler=null,delete this.sounds[a];return this},getSounds:function(){return $.extend(this.soundsCopy,this.sounds)},getSound:function(a){if(typeof a==="string")return this.sounds[a];else if(typeof a==="object"&&a.IGESound)return a}});unusing("IGE");unusing("IGE.Audio");unusing("General.Notification");using("IGE");using("IGE.Graphics");
define("IGE.Graphics.IGEImage").extend("IGEArea").assign({defaults:{x:0,y:0,width:0,height:0,strata:IGEStrata.moderate,id:"IGEImage",panel:"DEFAULT",source:""},source:null,handler:null,id:null,IGEImage:function(a){typeof a!=="object"&&(a={});this.IGEArea(a);this.source=a.source;this.id=a.id;a.hide&&this.hide();this.getDisplayElement().addClass("IGEImage");this.getDisplayElement().css("background","url('"+this.source+"') no-repeat");return this},_IGEImage:function(){}});unusing("IGE");unusing("IGE.Graphics");
using("IGE");using("IGE.Graphics");
define("IGE.Graphics.IGESprite").extend("IGEImage").assign({defaults:{x:0,y:0,width:0,height:0,strata:IGEStrata.moderate,id:"IGESprite",panel:"DEFAULT",source:"",spriteLeft:0,spriteTop:0},spriteTop:null,spriteLeft:null,IGESprite:function(a){this.IGEImage(a);this.getDisplayElement().addClass("IGESprite");this.setSpriteTop(a.spriteTop);this.setSpriteLeft(a.spriteLeft);return this},_IGESprite:function(){this._IGEImage()},setSpriteTop:function(a){if(typeof a!=="number")return null;this.spriteTop=-1*a;
this.updateSprite();return this},setSpriteLeft:function(a){if(typeof a!=="number")return null;this.spriteLeft=-1*a;this.updateSprite();return this},updateSprite:function(){this.getDisplayElement().css("background","url('"+this.source+"') "+this.spriteLeft+"px "+this.spriteTop+"px no-repeat");return this}});unusing("IGE");unusing("IGE.Graphics");
define("IGE.Graphics.IGEAnimation").assign({defaults:{interval:1E3,repeat:-1},id:null,images:null,cursor:null,interval:null,maximumRepeat:null,currentRepeat:null,timer:null,handler:null,IGEAnimation:function(a){var b;typeof a!=="object"&&(a={});this.id=typeof a.id==="string"?a.id:"IGEAnimation"+IGE.Graphics.IGEAnimation.index;IGE.Graphics.IGEAnimation.index++;this.maximumRepeat=typeof a.repeat==="number"?a.repeat:this.defaults.repeat;this.currentRepeat=0;this.images=[];if(typeof a.images==="object")if(a.images.IGEImage)this.addImage(a.images);
else for(b in a.images)this.addImage(a.images[b]);this.interval=typeof a.interval==="number"?a.interval:this.defaults.interval;this.cursor=0;return this},_IGEAnimation:function(){},addImage:function(a){if(!a.IGEImage)return null;this.images.splice(this.images.length,0,a);return this},removeImage:function(a){var b;if(typeof a!=="string")if(typeof a==="object"&&a.IGEImage)a=a.id;else return null;for(b in this.images)if(this.images[b].id===a){this.images.splice(b,1);break}return this},start:function(){var a=
this,b;if(a.handler){for(b in a.images)a.images[b].hide();a.currentRepeat=0;a.showNextImage();a.timer=setInterval(function(){a.showNextImage()},a.interval)}},stop:function(){clearInterval(this.timer)},showNextImage:function(){var a;a=this.images[this.cursor];this.cursor++;if(this.cursor==this.images.length)this.cursor=0,this.currentRepeat++;this.maximumRepeat>0&&this.currentRepeat>this.maximumRepeat&&this.stop();this.images[this.cursor].show();a.hide()},getCurrentImage:function(){return this.images[this.cursor]}});
IGE.Graphics.IGEAnimation.index=0;using("General.Notification");using("IGE");using("IGE.Graphics");
define("IGE.Graphics.IGEImageHandler").extend("Observer").assign({images:null,animations:null,area:null,IGEImageHandler:function(a){typeof a!=="object"&&(a={});this.area=a.area;this.images={};this.animations={};return this},_IGEImageHandler:function(){delete this.images},getArea:function(){return this.area},setBackgroundColor:function(a){this.area.getDisplayElement().css("background-color",a)},setBackgroundImage:function(a){this.area.getDisplayElement().css("background-image","url('"+a+"')")},addImage:function(a){if(typeof a!==
"object"||!a.IGEImage)throw new IGEInvalidTypeException("addImage takes only IGEImage objects.",this);if(this.images[a.id])try{this.removeImage(a.id)}catch(b){throw this.area.displayError("Caught an error while removing pre-existing image."),b;}this.images[a.id]=a;this.area.getDisplayElement().append(a.getDisplayElement());a.handler=this;return this},removeImage:function(a){if(typeof a!=="string")if(typeof a==="object"&&a.IGEImage)a=a.id;else throw new IGERemovalException("Unable to determine the id of image to remove.",
this);if(this.images[a])this.images[a].handler=null,this.area.getDisplayElement().remove(this.images[a].getDisplayElement()),delete this.images[a];return this},getImage:function(a){if(typeof a==="string")return this.images[a];else if(typeof a==="object"&&a.IGEImage)return a},addAnimation:function(a){if(typeof a!=="object"||!a.IGEAnimation)throw new IGEInvalidTypeException("addAnimation takes an IGEAnimation object.",this);if(this.animations[a.id])try{this.removeAnimation(a.id)}catch(b){throw this.area.displayError("Caught an error while removing pre-existing animation."),
b;}this.animations[a.id]=a;a.handler=this;return this},getAnimation:function(a){if(typeof a==="string")return this.animations[a];else if(typeof image==="object"&&a.IGEAnimation)return a},removeAnimation:function(a){if(typeof a!=="string")if(typeof image==="object"&&a.IGEAnimation)a=a.id;else throw new IGERemovalException("Unable to determine the id of animatione to remove.",this);if(this.animations[a])this.animations[a].handler=null,delete this.animations[a];return this}});unusing("IGE");unusing("IGE.Graphics");
unusing("General.Notification");using("IGE");using("IGE.Graphics");
define("IGELevel").extend("IGEArea").assign({defaults:{x:0,y:0,width:0,height:0,strata:IGEStrata.moderate,panel:"DEFAULT",id:"IGELevel"},children:null,IGELevel:function(a){var b;this.IGEArea(a);this.children={};this.getDisplayElement().addClass("IGELevel");if(typeof a.areas==="object")if($.isArray(a.areas))for(b in a.areas)this.add(a.areas[b]);else this.add(a.areas);return this},_IGELevel:function(){this._IGEArea();delete this.areas},add:function(a){if(typeof a!=="object"||!a.IGEArea)throw new IGE.Exceptions.IGEInvalidTypeException("add takes only IGEArea objects.",
this);this.getDisplayElement().append(a.getDisplayElement());this.children[a.getID()]=a;this.addObserver(a);a.setParent(this);return this},getChildren:function(){return this.children},pack:function(){var a,b=this.panel.getPos(),c,d,e;for(a in this.children)c=this.children[a].getPos(),d||(d=c.x+c.width),e||(e=c.y+c.height),c.x+c.width>d&&(d=c.x+c.width),c.y+c.height>e&&(e=c.y+c.height);if(d<b.width)d=b.width;if(e<b.height)e=b.height;this.setWidth(d);this.setHeight(e);return this},update:function(){this.notify()},
preLoad:function(){},postLoad:function(){}});unusing("IGE");unusing("IGE.Graphics");using("IGE");using("IGE.UI");using("IGE.Graphics");define("IGE.UI.IGEUserInterfaceObject").extend("IGEArea").assign({defaults:{x:0,y:0,width:0,height:0,strata:IGEStrata.moderate,id:"IGEUserInterfaceObject",panel:"DEFAULT"},id:null,IGEUserInterfaceObject:function(a){this.IGEArea(a);this.id=a.id;this.displayElement.addClass("IGEUserInterfaceObject");return this},_IGEUserInterfaceObject:function(){this._IGEArea()}});
unusing("IGE");unusing("IGE.UI");unusing("IGE.Graphics");using("IGE");using("IGE.UI");using("IGE.Graphics");
define("IGE.UI.IGEUserInterfaceButton").extend("IGEUserInterfaceObject").assign({defaults:{x:0,y:0,width:0,height:0,strata:IGEStrata.moderate,text:"",id:"IGEUserInterfaceButton",panel:"DEFAULT"},IGEUserInterfaceButton:function(a){var b=this;b.IGEUserInterfaceObject(a);b.getDisplayElement().addClass("IGEUserInterfaceButton");b.setText(a.text);if(typeof a.click==="function")b.click=a.click;b.getDisplayElement().click(function(a){b.click(a)});return b},_IGEUserInterfaceButton:function(){},setText:function(a){this.displayElement.text(a)},
click:function(){}});unusing("IGE");unusing("IGE.UI");unusing("IGE.Graphics");using("IGE");using("IGE.UI");using("IGE.Graphics");
define("IGE.UI.IGEUserInterfaceLabel").extend("IGEUserInterfaceObject").assign({defaults:{x:0,y:0,width:0,height:0,strata:IGEStrata.moderate,text:"",id:"IGEUserInterfaceLabel",panel:"DEFAULT"},IGEUserInterfaceLabel:function(a){this.IGEUserInterfaceObject(a);this.displayElement.addClass("IGEUserInterfaceLabel");this.setText(a.text);return this},_IGEUserInterfaceLabel:function(){this._IGEUserInterfaceObject()},setText:function(a){this.displayElement.text(a)}});unusing("IGE");unusing("IGE.UI");unusing("IGE.Graphics");
using("IGE");using("IGE.UI");using("IGE.Graphics");
define("IGE.UI.IGEUserInterfacePanel").extend("IGEUserInterfaceObject").assign({defaults:{x:0,y:0,width:0,height:0,strata:IGEStrata.moderate,id:"IGEUserInterfacePanel",panel:"DEFAULT"},userInterfaceObjects:null,IGEUserInterfacePanel:function(a){this.IGEUserInterfaceObject(a);this.userInterfaceObjects={};this.displayElement.addClass("IGEUserInterfacePanel");return this},_IGEUserInterfacePanel:function(){this._IGEUserInterfaceObject()},addObject:function(a){if(typeof a!=="object"||!a.IGEUserInterfaceObject)return null;
if(this.userInterfaceObjects[a.id]&&!this.removeObject(a.id))return null;this.displayElement.append(a.displayElement);this.addObserver(a);this.userInterfaceObjects[a.id]=a;return this},removeObject:function(a){if(typeof a!=="string")if(typeof a==="object"&&a.IGEUserInterfaceObject)a=a.id;else return null;this.userInterfaceObjects[a]&&(this.getDisplayElement().remove(this.userInterfaceObjects[a].getDisplayElement()),delete this.userInterfaceObjects[a]);return this},getObject:function(a){return typeof a===
"string"?this.userInterfaceObjects[a]:typeof a==="object"&&a.IGEUserInterfaceObject?a:null}});unusing("IGE");unusing("IGE.UI");unusing("IGE.Graphics");using("IGE");using("IGE.UI");define("IGE.UI.IGEUserInterfaceTextArea").extend("IGEUserInterfaceObject").assign({IGEUserInterfaceTextArea:function(){throw new IGEUnimplementedException("Currently unimplemented");},_IGEUserInterfaceTextArea:function(){}});unusing("IGE");unusing("IGE.UI");using("IGE");using("IGE.Graphics");
define("IGE.IGEConsole").extend("IGEArea").assign({defaults:{x:0,y:0,width:0,height:0,strata:IGEStrata.moderate,panel:"DEFAULT",id:"IGEConsole"},IGEConsole:function(a){this.IGEArea(a);this.getDisplayElement().addClass("IGEConsole");this.getDisplayElement().css("overflow","scroll");this.getDisplayElement().css("z-index","3");this.getDisplayElement().fadeTo(0,0.75);if(typeof a.panel==="string")a=getIGEPanel(a.panel);else if(typeof a.panel==="object"&&a.panel.IGEPanel)a=a.panel;else throw new IGEInvalidTypeException("IGEConsole requires a panel attribute as either an IGEPanel object or string id.",
this);if(a)a.getDisplayElement().append(this.getDisplayElement());else throw new IGEInvalidTypeException("No panel could be located matching the given criteria.",this);return this},_IGEConsole:function(){},log:function(a){this.message(a,"log")},info:function(a){this.message(a,"info")},warning:function(a){this.message(a,"warning")},error:function(a){this.message(a,"error")},message:function(a,b){var c=$(document.createElement("div"));c.addClass("message").addClass(b);c.html('<span class="'+b+'">'+
b+": </span>"+a+"<br/>");this.getDisplayElement().append(c);this.getDisplayElement().scrollTop(999999)}});unusing("IGE");unusing("IGE.Graphics");using("IGE");
define("IGESolidDirs").assign({top:!1,bottom:!1,left:!1,right:!1,IGESolidDirs:function(a){if(typeof a==="boolean")this.bottom=this.right=this.left=this.top=a;else{if(typeof a.top==="boolean")this.top=a.top;if(typeof a.bottom==="boolean")this.bottom=a.bottom;if(typeof a.left==="boolean")this.left=a.left;if(typeof a.right==="boolean")this.right=a.right}},_IGESolidDirs:function(){delete this}});unusing("IGE");using("IGE");using("IGE.Graphics");
define("IGE.IGEObject").extend("IGEArea").assign({defaults:{y:0,x:0,width:0,height:0,strata:IGEStrata.moderate,solidDirs:!1,friction:0,id:"IGEObject",panel:"DEFAULT",verbose:!1},solidDirs:null,solidDirsCopy:null,modifiers:null,IGEObject:function(a){typeof a!=="object"&&(a={});this.IGEArea(a);this.getDisplayElement().addClass("IGEObject");this.solidDirs=new IGESolidDirs(typeof a.solidDirs==="object"&&a.solidDirs.IGESolidDirs||typeof a.solidDirs==="boolean"?a.solidDirs:this.defaults.solidDirs);this.solidDirsCopy=
new IGESolidDirs(!1);this.debug("IGEObject: solid directions have been set.");this.debug("IGEObject construction finished.");return this},_IGEObject:function(){this._IGEArea()},getSolidDirs:function(){using("IGE.Modification");var a,b,c=this.solidDirsCopy;c.top=this.solidDirs.top;c.left=this.solidDirs.left;c.right=this.solidDirs.right;c.bottom=this.solidDirs.bottom;for(a in this.modifiers){if(this.modifiers[a].solidDirsTop&&(b=this.modifiers[a].solidDirsTop,b.type===IGEModifier.replace))c.top=b.value;
if(this.modifiers[a].solidDirsLeft&&(b=this.modifiers[a].solidDirsTop,b.type===IGEModifier.replace))c.left=b.value;if(this.modifiers[a].solidDirsRight&&(b=this.modifiers[a].solidDirsTop,b.type===IGEModifier.replace))c.right=b.value;if(this.modifiers[a].solidDirsBottom&&(b=this.modifiers[a].solidDirsTop,b.type===IGEModifier.replace))c.bottom=b.value}unusing("IGE.Modification");return c},removeModifier:function(a){var b;if(typeof a==="string")for(b in this.modifiers){if(this.modifiers[b][a]){this.modifiers[b].deactivate(this);
this.modifiers.splice(b,1);break}}else if(typeof a==="object"&&a.IGEObjectModifier)for(b in this.modifiers){if(this.modifiers[b]===a){this.modifiers[b].deactivate(this);this.modifiers.splice(b,1);break}}else throw this.displayError("removeModifier takes an IGEObjectModifier object or string"),new IGEInvalidTypeException("removeModifier takes an IGEObjectModifier object or string",this);return this}});unusing("IGE");unusing("IGE.Graphics");using("IGE");using("IGE.Modification");
define("IGE.Modification.IGEObjectModifier","abstract").extend("IGEAreaModifier").assign({solidDirsTop:null,solidDirsLeft:null,solidDirsRight:null,solidDirsBottom:null,activate:abstractFunction(IGEObject),deactivate:abstractFunction(IGEObject)});unusing("IGE");unusing("IGE.Modification");using("IGE.Control");
define("IGE.Control.IGEKeybind").assign({defaults:{keycode:0,keydown:function(){},keyup:function(){},description:"empty bind"},keycode:null,keydown:null,keyup:null,description:null,handler:null,IGEKeybind:function(a){typeof a!=="object"&&(a={});var b=typeof a.keydown==="function"?a.keydown:this.defaults.keydown,c=typeof a.keyup==="function"?a.keyup:this.defaults.keyup,d=typeof a.description==="string"?a.description:this.defaults.description;this.keycode=typeof a.keycode==="number"?a.keycode:this.defaults.keycode;
this.keydown=b;this.keyup=c;this.description=d;return this},_IGEKeybind:function(){},unbind:function(){return this.handler?this.handler.unbind(this):null}});unusing("IGE.Control");using("IGE.Control");using("IGE.Exceptions");
define("IGE.Control.IGEKeybindHandler").assign({defaults:{target:document},keybinds:null,panel:null,IGEKeybindHandler:function(a){var b=this,c;typeof a!=="object"&&(a={});if(typeof a.panel!=="object"||!a.panel.IGEPanel)throw new IGEInvalidTypeException("No panel entered for IGEKeybindHandler",b);b.keybinds=[];c=a.target?a.target:b.defaults.target;b.panel=a.panel;$(c).keydown(function(a){(a=b.keybinds[a.which])&&a.IGEKeybind&&a.keydown()});$(c).keyup(function(a){(a=b.keybinds[a.which])&&a.IGEKeybind&&
a.keyup()});return b},_IGEKeybindHandler:function(){delete this.keybinds},bind:function(a){if(!a.IGEKeybind)throw new IGEInvalidTypeException("bind takes an IGEKeybind object.",this);this.keybinds[a.keycode]=a;a.handler=this;return this},unbind:function(a){if(!a.IGEKeybind)throw new IGEInvalidTypeException("unbind takes an IGEKeybind object.",this);this.keybinds[a.keycode]=null;a.handler=null;return this},rebind:function(a,b){if(!a.IGEKeybind)throw new IGEInvalidTypeException("rebind takes an IGEKeybind object and a numeric keycode",
this);if(typeof b!=="number")throw new IGEInvalidTypeException("rebind takes an IGEKeybind object and a numeric keycode",this);try{this.unbind(a),a.keycode=b,this.bind(a)}catch(c){throw this.panel.displayError("An error occurred while rebinding a key."),c;}return this},getKeyToKeycode:function(a){return IGE.Control.IGEKeybindHandler.getKeyToKeycode(a)},getKeycodeToKey:function(a){return IGE.Control.IGEKeybindHandler.getKeycodeToKey(a)}});
IGE.Control.IGEKeybindHandler.getKeyToKeycode=function(a){if(typeof a==="string")return IGE.Control.IGEKeybindHandler.keyToKeycode[a]};IGE.Control.IGEKeybindHandler.getKeycodeToKey=function(a){if(typeof a==="number")return IGE.Control.IGEKeybindHandler.keycodeToKey[a]};
IGE.Control.IGEKeybindHandler.keyToKeycode={backspace:8,tab:9,enter:13,shift:16,ctrl:17,alt:18,"pause/break":19,"caps lock":20,escape:27,space:32,"page up":33,"page down":34,end:35,home:36,"left arrow":37,"up arrow":38,"right arrow":39,"down arrow":40,insert:45,"delete":46,0:48,1:49,2:50,3:51,4:52,5:53,6:54,7:55,8:56,9:57,a:65,b:66,c:67,d:68,e:69,f:70,g:71,h:72,i:73,j:74,k:75,l:76,m:77,n:78,o:79,p:80,q:81,r:82,s:83,t:84,u:85,v:86,w:87,x:88,y:89,z:90,"left window":91,"right window":92,select:93,"numpad 0":96,
"numpad 1":97,"numpad 2":98,"numpad 3":99,"numpad 4":100,"numpad 5":101,"numpad 6":102,"numpad 7":103,"numpad 8":104,"numpad 9":105,multiply:106,add:107,subtract:109,"decimal point":110,divide:111,f1:112,f2:113,f3:114,f4:115,f5:116,f6:117,f7:118,f8:119,f9:120,f10:121,f11:122,f12:123,"num lock":144,"scroll lock":145,"semi-colon":186,"equal sign":187,comma:188,dash:189,period:190,"forward slash":191,"grave accent":192,"open bracket":219,"back slash":220,"close braket":221,"single quote":222};
IGE.Control.IGEKeybindHandler.keycodeToKey=[void 0,void 0,void 0,void 0,void 0,void 0,void 0,"backspace","tab",void 0,void 0,void 0,"enter",void 0,void 0,"shift","control","alt","pause/break","caps-lock",void 0,void 0,void 0,void 0,void 0,void 0,"escape",void 0,void 0,void 0,void 0,"space","page-up","page-down","end","home","left arrow","up arrow","right arrow","down arrow",void 0,void 0,void 0,void 0,"insert","delete",void 0,"0","1","2","3","4","5","6","7","8","9",void 0,void 0,void 0,void 0,void 0,
void 0,void 0,"a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z","left window","right window","select",void 0,void 0,"numpad 0","numpad 1","numpad 2","numpad 3","numpad 4","numpad 5","numpad 6","numpad 7","numpad 8","numpad 9","multiply","add",void 0,"subtract","decimal point","divide","f1","f2","f3","f4","f5","f6","f7","f8","f9","f10","f11","f12",void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,
void 0,void 0,void 0,void 0,void 0,void 0,"num lock","scroll lock",void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,"semi-colon","equal","comma","dash","period","forward slash","grave accent",void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,
void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,"open bracket","backslash","close bracket","single quote"];unusing("IGE.Control");unusing("IGE.Exceptions");using("IGE");using("IGE.Graphics");
define("IGE.IGEPanel").extend("IGEArea").assign({defaults:{x:0,y:0,width:800,height:600,strata:IGEStrata.moderate,id:"IGEPanel",container:"body",framesPerSecond:30},updateTimer:null,gameObjects:null,gameObjectElement:null,userInterfaceObjects:null,userInterfaceElement:null,paused:!1,gameOver:!1,framesPerSecond:null,updateInterval:null,keybindHandler:null,console:null,level:null,focusObject:null,IGEPanel:function(a){typeof a!=="object"&&(a={});this.defaults.container=$(this.defaults.container);a.panel=
this;this.IGEArea(a);this.gameObjects=[];this.userInterfaceObjects=[];with(namespace("IGE")){if(typeof a.console==="object")a.console.IGEConsole?this.console=a.console:(a.console.panel=this,this.console=new IGEConsole(a.console));this.debug("IGEPanel: console has been created.")}this.framesPerSecond=a.framesPerSecond;this.updateInterval=1/this.framesPerSecond*1E3;this.debug("IGEPanel: update interval has been set to "+this.updateInterval+".");this.gameObjectElement=$(document.createElement("div"));
this.gameObjectElement.css("overflow","hidden");this.gameObjectElement.css("z-index","1");this.gameObjectElement.addClass("GameObjectElement");this.userInterfaceElement=$(document.createElement("div"));this.userInterfaceElement.css("overflow","hidden");this.userInterfaceElement.css("z-index","2");this.userInterfaceElement.addClass("UserInterfaceElement");this.displayElement.append(this.gameObjectElement);this.displayElement.append(this.userInterfaceElement);this.getDisplayElement().addClass("IGEPanel");
a.container.append(this.displayElement);with(IGE.Control)this.keybindHandler=new IGEKeybindHandler({panel:this}),this.debug("IGEPanel: keybind handler has been created.");this.focusObject=typeof a.focus==="object"&&a.focus.IGEArea?a.focus:null;this.debug("IGEPanel: focus object has been identified.");IGE_PANELS.DEFAULT||(IGE_PANELS.DEFAULT=this);IGE_PANELS[this.id]=this;this.debug("IGEPanel construction finished.");return this},_IGEPanel:function(){this._IGEObject()},setFocusObject:function(a){if(typeof a!==
"object"||!a.IGEArea)return null;this.focusObject=a;return this},update:function(){this.paused||(this.notify(),this.focusObject&&this.updateView())},updateView:function(){var a,b,c,d;if(!this.focusObject)return null;a=this.getPos();b=this.level.getPos();c=this.focusObject.getCenter();d=a.height/2-c.getY();c=a.width/2-c.getX();d>0&&(d=0);c>0&&(c=0);c+b.width<a.width&&(c=a.width-b.width);d+b.height<a.height&&(d=a.height-b.height);this.level.setPos(c,d);return this},add:function(a){return a.IGEObject||
a.IGESector?this.addGameResource(a):a.IGEUserInterfaceObject?this.addUserInterfaceResource(a):null},addGameResource:function(a){if(!a.IGEObject&&!a.IGESector)return null;this.addObserver(a);this.gameObjects.push(a);this.gameObjectElement.append(a.displayElement);return this},addUserInterfaceResource:function(a){if(!a.IGEUserInterfaceObject)return null;this.addObserver(a);this.userInterfaceObjects.push(a);this.userInterfaceElement.append(a.displayElement);return this},getChildren:function(){return this.gameObjects},
getGameObjects:function(){return this.gameObjects},getUserInterfaceObjects:function(){return this.userInterfaceObjects},getConsole:function(){return this.console},start:function(){var a=this;a.updateTimer=setInterval(function(){a.update()},a.updateInterval)},pause:function(){this.paused=!0},unpause:function(){this.paused=!1},pauseToggle:function(){this.paused=!this.paused},loadLevel:function(a){if(!a.IGELevel)throw new IGEInvalidTypeException("loadLevel takes an IGELevel object.",this);if(this.level)try{this.unloadLevel()}catch(b){throw this.displayError("Caught an error when unloading old level."),
b;}a.preLoad();this.gameObjectElement.append(a.getDisplayElement());this.addObserver(a);this.level=a;this.level.pack();a.postLoad();return this},unloadLevel:function(){if(!this.level)throw new IGERemovalException("There is no level to unload.",this);this.removeObserver(this.level);this.getDisplayElement().remove(this.level.getDisplayElement());this.level=null;return this},getKeybindHandler:function(){return this.keybindHandler},displayError:function(a){this.console&&this.console.error(a)},displayWarning:function(a){this.console&&
this.console.warning(a)},displayInfo:function(a){this.console&&this.console.info(a)}});var IGE_PANELS={};function getIGEPanel(a){return IGE_PANELS[a]}unusing("IGE");unusing("IGE.Graphics");using("IGE");using("IGE.Graphics");
define("IGE.IGELevelViewer").extend("IGEPanel").assign({defaults:{x:0,y:0,width:800,height:600,strata:IGEStrata.moderate,id:"IGEPanel",container:"body",framesPerSecond:35,scrollIncrement:25},moveUp:!1,moveLeft:!1,moveRight:!1,moveDown:!1,scrollIncrement:null,IGELevelViewer:function(a){var b=this,c=new IGEKeybind({keycode:IGEKeybindHandler.getKeyToKeycode("up arrow"),keydown:function(){b.moveUp=!0},keyup:function(){b.moveUp=!1},description:"Move the view upwards"}),d=new IGEKeybind({keycode:IGEKeybindHandler.getKeyToKeycode("left arrow"),
keydown:function(){b.moveLeft=!0},keyup:function(){b.moveLeft=!1},description:"Move the view left"}),e=new IGEKeybind({keycode:IGEKeybindHandler.getKeyToKeycode("right arrow"),keydown:function(){b.moveRight=!0},keyup:function(){b.moveRight=!1},description:"Move the view right"}),f=new IGEKeybind({keycode:IGEKeybindHandler.getKeyToKeycode("down arrow"),keydown:function(){b.moveDown=!0},keyup:function(){b.moveDown=!1},description:"Move the view down"});typeof a!=="object"&&(a={});b.IGEPanel(a);b.getDisplayElement().addClass("IGELevelViewer");
b.scrollIncrement=typeof a.scrollIncrement==="number"?a.scrollIncrement:b.defaults.scrollIncrement;b.focusObject={};a=b.getKeybindHandler();a.bind(c);a.bind(d);a.bind(e);a.bind(f);return b},_IGELevelViewer:function(){},updateView:function(){if(typeof this.level==="object"&&this.level.IGELevel){var a=this.level.getPos(),b=0,c=0;this.moveUp&&(c-=this.scrollIncrement);this.moveLeft&&(b+=this.scrollIncrement);this.moveRight&&(b-=this.scrollIncrement);this.moveDown&&(c+=this.scrollIncrement);this.level.setPos(a.x+
b,a.y+c)}}});unusing("IGE");unusing("IGE.Graphics");using("IGE");define("IGE.IGELevelEditor").extend("IGELevelViewer").assign({IGELevelEditor:function(){throw new IGEUnimplementedException("Currently unimplemented");},_IGELevelEditor:function(){}});unusing("IGE");using("IGE");using("IGE.Graphics");
define("IGE.IGEMovableObject").extend("IGEObject").assign({defaults:{x:0,y:0,width:0,height:0,strata:IGEStrata.moderate,solidDirs:!1,gravity:0,maxSpeed:0,accelleration:0,friction:0,id:"IGEMovableObject",panel:"DEFAULT",verbose:!1},gravity:null,gravityCopy:null,accelleration:null,accellerationCopy:null,maxSpeed:null,maxSpeedCopy:null,movement:null,stableHorizontal:null,stableVertical:null,moveLeft:!1,moveRight:!1,moveUp:!1,moveDown:!1,IGEMovableObject:function(a){this.IGEObject(a);this.movement=new IGEVector(0,
0);this.getDisplayElement().addClass("IGEMovableObject");if(typeof a.gravity==="number")this.gravity=new IGEVector(a.gravity,a.gravity);else if(typeof a.gravity==="object"&&typeof a.gravity.horizontal==="number"&&typeof a.gravity.vertical==="number")this.gravity=new IGEVector(a.gravity.horizontal,a.gravity.vertical);else if(typeof a.gravity==="object"&&a.gravity.IGEVector)this.gravity=a.gravity;else throw this.displayError("Invalid gravity specified for "+this.id+": "+a.gravity),new IGEInvalidTypeException("Invalid gravity specified for "+
this.id+": "+a.gravity,this);this.debug("IGEMovableObject: gravity vector has been set.");this.gravityCopy=new IGEVector(0,0);if(typeof a.accelleration==="number")this.accelleration=new IGEVector(a.accelleration,a.accelleration);else if(typeof a.accelleration==="object"&&typeof a.accelleration.horizontal==="number"&&typeof a.accelleration.vertical==="number")this.accelleration=new IGEVector(a.accelleration.horizontal,a.accelleration.vertical);else if(typeof a.accelleration==="object"&&a.accelleration.IGEVector)this.accelleration=
a.accelleration;else throw this.displayError("Invalid accelleration specified for "+this.id+": "+a.accelleration),new IGEInvalidTypeException("Invalid accelleration specified for "+this.id+": "+a.accelleration,this);this.debug("IGEMovableObject: accelleration vector has been set.");this.accellerationCopy=new IGEVector(0,0);if(typeof a.maxSpeed==="number")this.maxSpeed=new IGEVector(a.maxSpeed,a.maxSpeed);else if(typeof a.maxSpeed==="object"&&typeof a.maxSpeed.horizontal==="number"&&typeof a.maxSpeed.vertical===
"number")this.maxSpeed=new IGEVector(a.maxSpeed.horizontal,a.maxSpeed.vertical);else if(typeof a.maxSpeed==="object"&&a.maxSpeed.IGEVector)this.maxSpeed=a.maxSpeed;else throw this.displayError("Invalid maximum speed specified for "+this.id+": "+a.maxSpeed),new IGEInvalidTypeException("Invalid maximum speed specified for "+this.id+": "+a.maxSpeed,this);this.debug("IGEMovableObject: maximum speed values have been set.");this.maxSpeedCopy=new IGEVector(0,0);this.debug("IGEMovableObject construction finished.");
return this},_IGEMovableObject:function(){this._IGEObject()},getGravity:function(){var a,b;with(namespace("IGE.Modification"))for(a in this.gravityCopy.setX(this.gravity.getX()),this.gravityCopy.setY(this.gravity.getY()),this.modifiers){if(this.modifiers[a].gravityHorizontal)switch(b=this.modifiers[a].gravityHorizontal,b.type){case IGEObjectModifier.add:this.gravityCopy.addX(b.value);break;case IGEObjectModifier.subtract:this.gravityCopy.subtractX(b.value);break;case IGEObjectModifier.multiply:this.gravityCopy.multiplyX(b.value);
break;case IGEObjectModifier.divide:this.gravityCopy.divideX(b.value);break;case IGEObjectModifier.replace:this.gravityCopy.setX(b.value)}if(this.modifiers[a].gravityVertical)switch(b=this.modifiers[a].gravityVertical,b.type){case IGEObjectModifier.add:this.gravityCopy.addY(b.value);break;case IGEObjectModifier.subtract:this.gravityCopy.subtractY(b.value);break;case IGEObjectModifier.multiply:this.gravityCopy.multiplyY(b.value);break;case IGEObjectModifier.divide:this.gravityCopy.divideY(b.value);
break;case IGEObjectModifier.replace:this.gravityCopy.setY(b.value)}}return this.gravityCopy},getAccelleration:function(){var a,b;with(namespace("IGE.Modification"))for(a in this.accellerationCopy.setX(this.accelleration.getX()),this.accellerationCopy.setY(this.accelleration.getY()),this.modifiers){if(this.modifiers[a].accellerationHorizontal)switch(b=this.modifiers[a].accellerationHorizontal,b.type){case IGEModifier.add:this.accellerationCopy.addX(b.value);break;case IGEModifier.subtract:this.accellerationCopy.subtractX(b.value);
break;case IGEModifier.multiply:this.accellerationCopy.multiplyX(b.value);break;case IGEModifier.divide:this.accellerationCopy.divideX(b.value);break;case IGEModifier.replace:this.accellerationCopy.setX(b.value)}if(this.modifiers[a].accellerationVerticle)switch(b=this.modifiers[a].accellerationVerticle,b.type){case IGEModifier.add:this.accellerationCopy.addY(b.value);break;case IGEModifier.subtract:this.accellerationCopy.subtractY(b.value);break;case IGEModifier.multiply:this.accellerationCopy.multiplyY(b.value);
break;case IGEModifier.divide:this.accellerationCopy.divideY(b.value);break;case IGEModifier.replace:this.accellerationCopy.setY(b.value)}}return this.accellerationCopy},getMaxSpeed:function(){var a,b;with(namespace("IGE.Modification"))for(a in this.maxSpeedCopy.setX(this.maxSpeed.getX()),this.maxSpeedCopy.setY(this.maxSpeed.getY()),this.modifiers){if(this.modifiers[a].maxSpeedHorizontal)switch(b=this.modifiers[a].maxSpeedHorizontal,b.type){case IGEModifier.add:this.maxSpeedCopy.addX(b.value);break;
case IGEModifier.subtract:this.maxSpeedCopy.subtractX(b.value);break;case IGEModifier.multiply:this.maxSpeedCopy.multiplyX(b.value);break;case IGEModifier.divide:this.maxSpeedCopy.divideX(b.value);break;case IGEModifier.replace:this.maxSpeedCopy.setX(b.value)}if(this.modifiers[a].maxSpeedVerticle)switch(b=this.modifiers[a].maxSpeedVerticle,b.type){case IGEModifier.add:this.maxSpeedCopy.addY(b.value);break;case IGEModifier.subtract:this.maxSpeedCopy.subtractY(b.value);break;case IGEModifier.multiply:this.maxSpeedCopy.multiplyY(b.value);
break;case IGEModifier.divide:this.maxSpeedCopy.divideY(b.value);break;case IGEModifier.replace:this.maxSpeedCopy.setY(b.value)}}return this.maxSpeedCopy},updateState:function(){this.updatePosition()},updatePosition:function(){var a,b=this.getPos(),c=this.parent.getChildren(),d;this.factorGravity();this.factorFriction();this.factorMovementFlags();this.factorMaxSpeed();for(a in c)d=c[a],d!=this&&(this.checkForIntersectionDown(d),this.checkForIntersectionUp(d),this.checkForIntersectionLeft(d),this.checkForIntersectionRight(d));
this.checkIfFallOff();this.setPos(b.x+this.movement.getX(),b.y+this.movement.getY())},factorMovementFlags:function(){var a=this.getAccelleration();this.movingLeft&&this.movement.subtractX(a.getX());this.movingRight&&this.movement.addX(a.getX());this.movingUp&&this.movement.addY(a.getY());this.movingDown&&this.movement.subtractY(a.getY())},factorFriction:function(){var a,b;this.stableVertical&&(a=this.stableVertical.getFriction(),b=a.getX(),this.movement.getX()>0?this.movement.getX()>b?this.movement.subtractX(b):
this.movement.setX(0):this.movement.getX()<0&&(Math.abs(this.movement.getX())>b?this.movement.addX(b):this.movement.setX(0)));this.stableHorizontal&&(a=this.stableHorizontal.getFriction(),b=a.getY(),this.movement.getY()>0?this.movement.getY()>b?this.movement.subtractY(b):this.movement.setY(0):this.movement.getY()<0&&(Math.abs(this.movement.getY())>b?this.movement.addY(b):this.movement.setY(0)));a=this.getParent().getFriction();b=a.getY();this.movement.getY()>0?this.movement.getY()>b?this.movement.subtractY(b):
this.movement.setY(0):this.movement.getY()<0&&(Math.abs(this.movement.getY())>b?this.movement.addY(b):this.movement.setY(0));b=a.getX();this.movement.getX()>0?this.movement.getX()>b?this.movement.subtractX(b):this.movement.setX(0):this.movement.getX()<0&&(Math.abs(this.movement.getX())>b?this.movement.addX(b):this.movement.setX(0))},factorGravity:function(){var a=this.getGravity();this.stableHorizontal?this.movement.setX(0):this.movement.addX(-1*a.getX());this.stableVertical?this.movement.setY(0):
this.movement.addY(-1*a.getY())},factorMaxSpeed:function(){var a=this.getMaxSpeed();this.movement.getX()<-1*a.getX()&&this.movement.setX(-1*a.getX());this.movement.getX()>a.getX()&&this.movement.setX(a.getX());this.movement.getY()>a.getY()&&this.movement.sexY(a.getY());this.movement.getY()<-1*a.getY()&&this.movement.setY(-1*a.getY())},checkForIntersectionDown:function(a){var b=this.movement,c=a.getPos(),d=this.getPos();if(this.intersectsXOffset(a,b.getX())&&this.isAbove(a)&&(this.intersectsYOffset(a,
b.getY())||this.isBelowOffset(a,b.getY())))if(this.interactWith(a),a.interactWith(this),a.IGEObject&&a.getSolidDirs().top){if(this.impact(a),this.movement.setY(0),this.setPos(d.x,c.y+c.height),this.gravity.getY()>0)this.stableVertical=a}else a.IGESector&&a.activate(this)},checkForIntersectionUp:function(a){var b=this.movement,c=a.getPos(),d=this.getPos();if(this.intersectsXOffset(a,b.getX())&&this.isBelow(a)&&(this.intersectsYOffset(a,b.getY())||this.isAboveOffset(a,b.getY())))if(this.interactWith(a),
a.interactWith(this),a.IGEObject&&a.getSolidDirs().bottom){if(this.impact(a),this.movement.setY(0),this.setPos(d.x,c.y-d.height),this.gravity.getY()<0)this.stableVertical=a}else a.IGESector&&a.activate(this)},checkForIntersectionLeft:function(a){var b=this.movement,c=a.getPos(),d=this.getPos();if(this.intersectsYOffset(a,b.getY())&&this.isRightOf(a)&&(this.intersectsXOffset(a,b.getX())||this.isLeftOfOffset(a,b.getX())))if(this.interactWith(a),a.interactWith(this),a.IGEObject&&a.getSolidDirs().right){if(this.impact(a),
this.movement.setX(0),this.setPos(c.x+c.width,d.y),this.gravity.getX()>0)this.stableHorizontal=a}else a.IGESector&&a.activate(this)},checkForIntersectionRight:function(a){var b=this.movement,c=a.getPos(),d=this.getPos();if(this.intersectsYOffset(a,b.getY())&&this.isLeftOf(a)&&(this.intersectsXOffset(a,b.getX())||this.isRightOfOffset(a,b.getX())))if(this.interactWith(a),a.interactWith(this),a.IGEObject&&a.getSolidDirs().left){if(this.impact(a),this.movement.setX(0),this.setPos(c.x-d.width,d.y),this.gravity.getX()<
0)this.stableHorizontal=a}else a.IGESector&&a.activate(this)},checkIfFallOff:function(){if(this.stableHorizontal&&!this.intersectsYOffset(this.stableHorizontal,this.movement.getY()))this.stableHorizontal=null;if(this.stableVertical&&!this.intersectsXOffset(this.stableVertical,this.movement.getX()))this.stableVertical=null}});unusing("IGE");unusing("IGE.Graphics");using("IGE");using("IGE.Modification");
define("IGE.Modification.IGEMovableObjectModifier","abstract").extend("IGEObjectModifier").assign({accellerationHorizontal:null,accellerationVertical:null,maxSpeedHorizontal:null,maxSpeedVertical:null,gravityHorizonal:null,gravityVertical:null,activate:abstractFunction(IGEMovableObject),deactivate:abstractFunction(IGEMovableObject)});unusing("IGE");unusing("IGE.Modification");using("IGE");
define("IGE.IGETargeter","abstract").assign({target:null,targetX:null,targetY:null,setTarget:function(a,b){if(typeof a==="object"&&a.IGEArea)this.target=a,this.targetX=a.getCenter().x,this.targetY=a.getCenter().y;else if(typeof a==="number"&&typeof b==="number")this.target=null,this.targetX=a,this.targetY=b;else throw IGEError("Invalid target set.");return this},getTarget:function(){if(this.target)return this.target;return{targetX:this.targetX,targetY:this.targetY}},moveToTarget:abstractFunction()});
unusing("IGE");using("IGE");using("IGE.Exceptions");using("IGE.Graphics");
define("IGE.IGECharacter","abstract").extend("IGEMovableObject","IGETargeter").assign({defaults:{x:0,y:0,width:0,height:0,gravity:0,maxSpeed:0,accelleration:0,friction:0,solidDirs:!1,strata:IGEStrata.moderate,hitpoints:1,id:"IGECharacter",panel:"DEFAULT",verbose:!1},currentHitpoints:null,maximumHitpoints:null,IGECharacter:function(a){this.IGEMovableObject(a);this.getDisplayElement().addClass("IGECharacter");this.maximumHitpoints=this.currentHitpoints=a.hitpoints;this.debug("IGECharacter: hitpoints have been set to "+
a.hitpoints);this.debug("IGECharacter construction finished.");return this},_IGECharacter:function(){this._IGEMovableObject()},setMaximumHitpoints:function(a){if(typeof a!=="number")throw new IGEInvalidTypeException("setMaximumHitpoints takes a number.",this);this.maximumHitpoints=a},getMaximumHitpoints:function(){return this.maximumHitpoints},setCurrentHitpoints:function(a){if(typeof a!=="number")throw new IGEInvalidTypeException("setCurrentHitpoints takes a number.",this);this.currentHitpoints=
a},getCurrentHitpoints:function(){return this.currentHitpoints},receiveDamage:function(a){if(typeof a!=="number")throw new IGEInvalidTypeException("receiveDamage takes a number.",this);this.currentHitpoints-=a}});unusing("IGE");unusing("IGE.Exceptions");unusing("IGE.Graphics");using("IGE");using("IGE.Modification");define("IGE.Modification.IGECharacterModifier","abstract").extend("IGEMovableObjectModifier").assign({maxHitpoints:null,currentHitpoints:null,activate:abstractFunction(IGECharacter),deactivate:abstractFunction(IGECharacter)});
unusing("IGE");unusing("IGE.Modification");using("IGE.Modification");define("IGE.Modification.IGEBuff","abstract").extend("IGECharacterModifier");unusing("IGE.Modification");using("IGE.Modification");define("IGE.Modification.IGEDebuff","abstract").extend("IGECharacterModifier");unusing("IGE.Modification");using("IGE");using("IGE.Graphics");
define("IGE.IGEPlayerCharacter").extend("IGECharacter").assign({defaults:{x:0,y:0,width:0,height:0,gravity:0,maxSpeed:0,accelleration:0,friction:0,solidDirs:!1,strata:IGEStrata.moderate,hitpoints:1,id:"IGEPlayerCharacter",panel:"DEFAULT",verbose:!1},IGEPlayerCharacter:function(a){this.IGECharacter(a);this.debug("IGEPlayerCharacter construction finished.");return this},_IGEPlayerCharacter:function(){this._IGECharacter()}});unusing("IGE");unusing("IGE.Graphics");using("IGE");
define("IGE.IGENonPlayerCharacter").extend("IGECharacter").assign({IGENonPlayerCharacter:function(a){this.IGECharacter(a);return this},_IGENonPlayerCharacter:function(){this._IGECharacter()}});unusing("IGE");using("IGE");define("IGE.IGEMovingPlatform").extend("IGEMovableObject").assign({IGEMovingPlatform:function(a){this.IGEMovableObject(a);return this},_IGEMovingPlatform:function(){this._IGEMovableObject()}});unusing("IGE");using("IGE");
define("IGE.IGECircuitPlatform").extend("IGEMovingPlatform").assign({IGECircuitPlatform:function(a){this.IGEMovingPlatform(a);return this},_IGECircuitPlatform:function(){this._IGEMovingPlatform()}});unusing("IGE");using("IGE");define("IGE.IGERotationalPlatform").extend("IGEMovingPlatform").assign({IGERotationalPlatform:function(a){this.IGEMovingPlatform(a);return this},_IGERotationalPlatform:function(){this._IGEMovingPlatform()}});unusing("IGE");using("IGE");using("IGE.Graphics");
define("IGE.IGESector").extend("IGEArea").assign({defaults:{x:0,y:0,width:0,height:0,strata:IGEStrata.background1,id:"IGESector"},containedObjects:null,IGESector:function(a){this.IGEArea(a);this.containedObjects={};if(typeof a.enter==="function")this.objectEnter=a.enter;if(typeof a.leave==="function")this.objectLeave=a.leave;return this},_IGESector:function(){this._IGEArea();delete this.containedObjects},include:function(a){if(typeof a!=="object"||!a.IGEArea)throw new IGEInvalidTypeException("include takes IGEArea objects.",
this);this.containedObjects[a.id]||(this.containedObjects[a.id]=a,this.objectEnter(a))},exclude:function(a){if(typeof a!=="object"||!a.IGEArea)throw new IGEInvalidTypeException("exclude takes IGEArea objects.",this);this.containedObjects[a.id]&&(delete this.containedObjects[a.id],this.objectLeave(a))},objectEnter:function(){},objectLeave:function(){},activate:function(a){if(typeof a!=="object"||!a.IGEArea)throw new IGEInvalidTypeException("activate takes IGEArea objects.",this);this.containedObjects[a.id]||
this.include(a)},update:function(){for(var a in this.containedObjects)this.intersects(this.containedObjects[a])||this.exclude(this.containedObjects[a])}});unusing("IGE");unusing("IGE.Graphics");using("IGE");using("IGE.Graphics");define("IGETimedSector").extend("IGESector").assign({defaults:{x:0,y:0,width:0,height:0,strata:IGEStrata.moderate,id:"IGETimedSector"},IGETimedSector:function(a){this.IGESector(a);return this},_IGETimedSector:function(){this._IGESector()}});unusing("IGE");unusing("IGE.Graphics");
